[constants]
CACHES = 116
N = 32
PEEK_PERIOD = [228, 288]
MAX_SAMPLES_PER_DAY = 40

[paths]
# Paths to the data files and directories
csv_data = "data/csv/"
# Paths to the preprocessed data and directories
preprocessed_data = "data/preprocessed"

# Paths to the model checkpoints
model_ckpt = "ckpts"

# Paths to the logs
log_dir = "logs"

[params]
network_architecture = [116, 120, 80, 116]
learning_rate = 0.007
training_interval = 2
batch_size = 128
memory_size = 1024
beta1 = 0.09
beta2 = 0.999
weight_decay = 0.0001
max_users = 2000
