[workspace]
authors = ["ShengRen <rensheng0410@outlook.com>"]
channels = ["conda-forge"]
name = "CacheFlux"
platforms = ["win-64"]
version = "0.1.0"

[feature.gpu.system-requirements]
cuda = "12.0"

[feature.gpu.dependencies]
cuda-version = "12.6.*"
pytorch-gpu = "*"

[feature.cpu.dependencies]
pytorch-cpu = "*"


[environments]
cpu = ["cpu"]
default = ["gpu"]

[tasks]

[dependencies]
numpy="*"
pandas="*"
pandas-stubs="*"
scipy="*"
scipy-stubs="*"
ruff="*"
matplotlib="*"
pulp="*"
pathlib="*"
rich="*"
mypy="*"
pytorch-lightning ="*"
python = ">=3.11"
fire = "*"

[pypi-dependencies]
matplotlib-stubs="*"
